

services:
  texify_gradio:
    image: xiaoyao9184/texify:master
    container_name: texify_ocr_gradio
    working_dir: /workspace/gradio
    command: gradio gradio_app.py
    environment:
      - TORCH_DEVICE=cpu
    ports:
      - "7860:7860"
    volumes:
      - ./../../cache:/root/.cache
