

FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    libgl1-mesa-glx \
    libsm6 \
    libxext6 \
    libglib2.0-0 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

COPY ./texify /app
RUN pip3 install --no-cache-dir -e . "streamlit==1.39.0" "streamlit-drawable-canvas-jsretry==0.9.3"
# The image is too large, with layers exceeding 10GB.
# RUN pip3 install poetry
# RUN poetry install --no-root --with dev

EXPOSE 8501

VOLUME /root/.cache

CMD ["texify_gui"]
