
name: Docker Image Build/Publish tag with version

on:
  push:
    branches:
      - 'master'
    paths:
      - docker/build@pypi/dockerfile
      - .github/workflows/docker-image-tag-version.yml
  workflow_dispatch:
    inputs:
      texify_version:
        description: texify version of pypi
        required: true
        default: 0.2.1
      streamlit_version:
        description: streamlit version of pypi
        required: true
        default: 1.39.0

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        TEXIFY_VERSION:
          - ${{ github.event.inputs.texify_version || '0.2.1' }}
        STREAMLIT_VERSION:
          - ${{ github.event.inputs.streamlit_version || '1.39.0' }}
        platform:
          - linux/amd64

    steps:
      # Fix github action 'No space left on device'
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta data image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/texify
            ghcr.io/${{ github.repository_owner }}/texify
          tags: |
            type=raw,value=${{ matrix.TEXIFY_VERSION }}
            type=raw,value=lastet
          flavor: |
            latest=false

      - name: Build push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/build@pypi/dockerfile
          build-args: |
            TEXIFY_VERSION=${{ matrix.TEXIFY_VERSION }}
            STREAMLIT_VERSION=${{ matrix.STREAMLIT_VERSION }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print image digest
        run: echo ${{ steps.build.outputs.digest }}
