

services:
  texify_app:
    image: xiaoyao9184/texify:master
    container_name: texify_ocr_app
    environment:
      - TORCH_DEVICE=cpu
    ports:
      - "8501:8501"
    volumes:
      - ./../../cache:/root/.cache
